"""Regenerate promptfooconfig.yaml from a RedBench plugin's probes.

RedBench stays the single source of truth for *what* gets tested (the
AttackPrompt list a plugin returns). This script exports that list into
Promptfoo's `intent` plugin config, so Promptfoo's engine — its transform
strategies (jailbreak wrapping, encoding, multi-turn crescendo, etc.) and
its grader — runs the actual attacks and scoring instead of RedBench's own
(placeholder) heuristic judge.

Usage:
    python promptfoo/generate_config.py --plugin redbench
    python promptfoo/generate_config.py --plugin redbench --out promptfooconfig.yaml
"""

from __future__ import annotations

import argparse
import os
import sys

import yaml

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from redbench.core.registry import default_registry
from redbench.plugins.redbench_plugin.plugin import RedBenchPlugin

default_registry.register(RedBenchPlugin)


def build_config(plugin_name: str) -> dict:
    plugin_cls = default_registry.get(plugin_name)
    plugin = plugin_cls()
    prompts = [p.prompt for p in plugin.generate_prompts()]

    return {
        "description": f"RedBench probes ({plugin_name}) executed via Promptfoo",
        "targets": [
            {
                "id": "file://promptfoo/provider.py",
                "label": "redbench-target",
            }
        ],
        "redteam": {
            "purpose": "A target model/agent under evaluation by the RedBench project.",
            "numTests": len(prompts),
            "plugins": [
                {
                    "id": "intent",
                    "config": {"intent": prompts},
                }
            ],
            "strategies": [
                "jailbreak",  # iterative refinement wrapper around each intent
                "crescendo",  # multi-turn: gradually escalates harm across turns
            ],
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--plugin", default="redbench", help="RedBench plugin name to export.")
    parser.add_argument(
        "--out",
        default=os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "promptfooconfig.yaml"),
        help="Where to write the generated config.",
    )
    args = parser.parse_args()

    config = build_config(args.plugin)
    with open(args.out, "w") as f:
        f.write("# Auto-generated by promptfoo/generate_config.py — do not hand-edit the\n")
        f.write("# `redteam.plugins[0].config.intent` list, edit the RedBench plugin's\n")
        f.write("# seed prompts instead and re-run this script.\n")
        yaml.safe_dump(config, f, sort_keys=False, allow_unicode=True)

    print(f"Wrote {args.out} with {len(config['redteam']['plugins'][0]['config']['intent'])} intents "
          f"from plugin '{args.plugin}'.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
